spring:
  application:
    name: product
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATA_USERNAME}
    password: ${SPRING_DATA_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  dotenv:
    file: ../.env

server:
  port: 8081
