server:
  port: 8181
spring:
  application:
    name: sell-bff
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Matcha
        registration:
          api-client:
            provider: keycloak
            client-id: sell-bff
            client-secret: L1ISNRVOUfQONER3aTs1OPaXGg0EZMTe #gitleaks:allow
            scope: openid, profile, email, roles
management:
  tracing:
    sampling:
      probability: "1.0"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      routes:
        # Changes for your local development should not be committed
        - id: api_product_local
          uri: http://localhost:8081
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api
          uri: http://api.matcha.local
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
